 version: 2

build:
  image: latest

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Install regular dependencies.
# Then, install special pinning for RTD.
python:
  version: 3.6
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all
